# Generated by Django 4.2.4 on 2023-08-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
